import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Streamdown } from "streamdown";
import { useAuth } from "@/_core/hooks/useAuth";
import { useLocation } from "wouter";

const POPULAR_BOOKS = [
  "Atomic Habits",
  "Rich Dad Poor Dad",
  "The Alchemist",
  "Think and Grow Rich",
  "Ikigai",
  "The Psychology of Money",
];

export default function Home() {
  const [bookName, setBookName] = useState("");
  const [searched, setSearched] = useState("");
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  
  const getSummaryMutation = trpc.bookExplainer.getSummary.useMutation();
  const getCurrentPlanQuery = trpc.subscription.getCurrentPlan.useQuery();
  const saveSummaryMutation = trpc.bookExplainer.saveSummary.useMutation();

  const handleSearch = async () => {
    if (!bookName.trim()) return;
    setSearched(bookName.trim());
    await getSummaryMutation.mutateAsync({ bookName: bookName.trim() });
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter") {
      handleSearch();
    }
  };

  const handleQuickSelect = (book: string) => {
    setBookName(book);
    setSearched(book);
    getSummaryMutation.mutateAsync({ bookName: book });
  };

  const handleDownloadPDF = async () => {
    if (!summary) return;

    try {
      // Dynamically import html2pdf
      const html2pdf = (await import("html2pdf.js")).default;

      const element = document.createElement("div");
      element.innerHTML = `
        <div style="font-family: 'Georgia', Arial, sans-serif; line-height: 1.8; color: #333; padding: 40px;">
          <h1 style="color: #d4a574; border-bottom: 3px solid #d4a574; padding-bottom: 15px; font-size: 28px; margin-bottom: 20px;">
            ${searched}
          </h1>
          <div style="font-size: 14px; color: #666; margin-bottom: 20px;">
            <p><strong>Generated by:</strong> Deepak Book Explainer</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString("en-US")}</p>
          </div>
          <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
          <div style="margin: 20px 0; font-size: 14px; line-height: 1.8;">
            ${summary}
          </div>
          <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;">
          <div style="margin-top: 40px; border-top: 1px solid #ddd; padding-top: 20px; font-size: 12px; color: #666;">
            <p>Email for feedback: deepakg151089@gmail.com</p>
            <p>Contact: Deepak Gupta - 8840778831</p>
          </div>
        </div>
      `;

      const options = {
        margin: 10,
        filename: `${searched.replace(/\s+/g, "_")}_summary.pdf`,
        image: { type: "jpeg" as const, quality: 0.98 },
        html2canvas: { scale: 2 },
        jsPDF: { orientation: "portrait" as const, unit: "mm" as const, format: "a4" as const },
      };

      (html2pdf as any)().set(options).from(element).save();
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  const handleSaveSummary = async () => {
    if (!summary || !user) return;
    await saveSummaryMutation.mutateAsync({
      bookTitle: searched,
      summary,
      bookId: getSummaryMutation.data?.metadata?.id,
    });
  };

  const summary = getSummaryMutation.data?.summary;
  const metadata = getSummaryMutation.data?.metadata;
  const isLoading = getSummaryMutation.isPending;
  const error = getSummaryMutation.error;
  const currentPlan = getCurrentPlanQuery.data;

  return (
    <div
      style={{
        minHeight: "100vh",
        background: "linear-gradient(135deg, #f5f1ed 0%, #faf8f5 50%, #f0ebe5 100%)",
        fontFamily: "'Georgia', 'Times New Roman', serif",
        padding: "0 0 60px",
      }}
    >
      {/* Header */}
      <div style={{ textAlign: "center", padding: "48px 20px 32px" }}>
        <div style={{ fontSize: 52, marginBottom: 8 }}>📚</div>
        <h1
          style={{
            fontSize: "clamp(28px, 6vw, 46px)",
            fontWeight: 900,
            color: "#d4a574",
            margin: "0 0 8px",
            letterSpacing: "-1px",
            fontFamily: "'Georgia', serif",
          }}
        >
          Deepak Book Explainer
        </h1>
        <p
          style={{
            fontSize: "clamp(14px, 3vw, 18px)",
            color: "#8b7355",
            margin: "0 0 24px",
            fontStyle: "italic",
          }}
        >
          Get instant AI-powered book summaries. Read any book in 10 minutes! 💡
        </p>

        {/* Subscription Status */}
        {currentPlan && (
          <div
            style={{
              display: "inline-block",
              padding: "8px 16px",
              background: currentPlan.isFreeTier ? "#ede6dd" : "#d4a574",
              color: currentPlan.isFreeTier ? "#8b7355" : "#fff",
              borderRadius: "20px",
              fontSize: "12px",
              fontWeight: "bold",
              marginBottom: "16px",
            }}
          >
            {currentPlan.planName} • {currentPlan.summariesUsedToday}/{currentPlan.summariesPerDay} summaries today
          </div>
        )}
      </div>

      {/* Search Section */}
      <div
        style={{
          maxWidth: "700px",
          margin: "0 auto 40px",
          padding: "0 20px",
        }}
      >
        <div style={{ display: "flex", gap: "12px", marginBottom: "24px" }}>
          <Input
            type="text"
            placeholder="Enter book name... e.g., 'Atomic Habits' or 'Rich Dad Poor Dad'"
            value={bookName}
            onChange={(e) => setBookName(e.target.value)}
            onKeyDown={handleKeyDown}
            style={{
              flex: 1,
              padding: "12px 16px",
              background: "#fff",
              border: "2px solid #d4a574",
              color: "#333",
              borderRadius: "8px",
              fontSize: "14px",
            }}
          />
          <Button
            onClick={handleSearch}
            disabled={isLoading}
            style={{
              padding: "12px 24px",
              background: "#d4a574",
              color: "#fff",
              border: "none",
              borderRadius: "8px",
              fontWeight: "bold",
              cursor: isLoading ? "not-allowed" : "pointer",
              opacity: isLoading ? 0.6 : 1,
            }}
          >
            {isLoading ? "⏳" : "Samjhao (Explain)"}
          </Button>
        </div>

        {/* Popular Books */}
        <div style={{ marginBottom: "32px" }}>
          <p style={{ color: "#8b7355", fontSize: "12px", marginBottom: "12px", textTransform: "uppercase", letterSpacing: "1px" }}>
            Popular Books
          </p>
          <div style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>
            {POPULAR_BOOKS.map((book) => (
              <button
                key={book}
                onClick={() => handleQuickSelect(book)}
                style={{
                  padding: "8px 16px",
                  background: "#ede6dd",
                  color: "#d4a574",
                  border: "2px solid #d4a574",
                  borderRadius: "20px",
                  cursor: "pointer",
                  fontSize: "13px",
                  fontWeight: "500",
                  transition: "all 0.2s",
                }}
                onMouseEnter={(e) => {
                  (e.target as HTMLButtonElement).style.background = "#d4a574";
                  (e.target as HTMLButtonElement).style.color = "#fff";
                }}
                onMouseLeave={(e) => {
                  (e.target as HTMLButtonElement).style.background = "#ede6dd";
                  (e.target as HTMLButtonElement).style.color = "#d4a574";
                }}
              >
                {book}
              </button>
            ))}
          </div>
        </div>
      </div>

      {/* Loading State */}
      {isLoading && (
        <div style={{ textAlign: "center", padding: "60px 20px" }}>
          <div style={{ fontSize: "48px", marginBottom: "16px", animation: "spin 2s linear infinite" }}>
            📖
          </div>
          <p style={{ color: "#8b7355", fontSize: "16px" }}>
            Generating your book summary... Please wait! 📚
          </p>
          <style>{`
            @keyframes spin {
              0% { transform: rotate(0deg); }
              100% { transform: rotate(360deg); }
            }
          `}</style>
        </div>
      )}

      {/* Error State */}
      {error && !isLoading && (
        <div
          style={{
            maxWidth: "700px",
            margin: "40px auto",
            padding: "20px",
            background: "#fde8e8",
            border: "2px solid #d4a574",
            borderRadius: "8px",
            color: "#c44545",
            textAlign: "center",
          }}
        >
          <p style={{ margin: "0", fontSize: "16px" }}>
            ❌ {error.message || "Something went wrong! Please try again."}
          </p>
        </div>
      )}

      {/* Summary Display */}
      {summary && !isLoading && (
        <div
          style={{
            maxWidth: "800px",
            margin: "40px auto",
            padding: "0 20px",
          }}
        >
          {/* Book Metadata Card */}
          {metadata && (
            <div
              style={{
                display: "flex",
                gap: "20px",
                marginBottom: "30px",
                padding: "20px",
                background: "#fff",
                borderRadius: "12px",
                border: "2px solid #d4a574",
                boxShadow: "0 4px 12px rgba(212, 165, 116, 0.1)",
              }}
            >
              {metadata.coverUrl && (
                <img
                  src={metadata.coverUrl}
                  alt={metadata.title}
                  style={{
                    width: "120px",
                    height: "180px",
                    borderRadius: "8px",
                    objectFit: "cover",
                  }}
                />
              )}
              <div style={{ flex: 1 }}>
                <h2 style={{ color: "#d4a574", margin: "0 0 8px", fontSize: "20px" }}>
                  {metadata.title}
                </h2>
                {metadata.author && (
                  <p style={{ color: "#8b7355", margin: "0 0 8px", fontSize: "14px" }}>
                    ✍️ {metadata.author}
                  </p>
                )}
                {metadata.rating && (
                  <p style={{ color: "#d4a574", margin: "0 0 8px", fontSize: "14px" }}>
                    ⭐ {metadata.rating}/5
                  </p>
                )}
                {metadata.publishedDate && (
                  <p style={{ color: "#8b7355", margin: "0", fontSize: "13px" }}>
                    📅 {metadata.publishedDate}
                  </p>
                )}
              </div>
            </div>
          )}

          {/* Summary Content */}
          <div
            style={{
              padding: "30px",
              background: "#fff",
              borderRadius: "12px",
              border: "2px solid #d4a574",
              marginBottom: "20px",
              color: "#333",
              lineHeight: "1.8",
              boxShadow: "0 4px 12px rgba(212, 165, 116, 0.1)",
            }}
          >
            <Streamdown>{summary}</Streamdown>
          </div>

          {/* Action Buttons */}
          <div style={{ display: "flex", gap: "12px", justifyContent: "center", flexWrap: "wrap" }}>
            <button
              onClick={handleDownloadPDF}
              style={{
                padding: "12px 24px",
                background: "#d4a574",
                color: "#fff",
                border: "none",
                borderRadius: "8px",
                fontWeight: "bold",
                cursor: "pointer",
                fontSize: "14px",
              }}
            >
              📥 Download PDF
            </button>
            {user && (
              <Button
                onClick={handleSaveSummary}
                disabled={saveSummaryMutation.isPending}
                style={{
                  padding: "12px 24px",
                  background: "#ede6dd",
                  color: "#d4a574",
                  border: "2px solid #d4a574",
                  borderRadius: "8px",
                  fontWeight: "bold",
                  cursor: saveSummaryMutation.isPending ? "not-allowed" : "pointer",
                }}
              >
                {saveSummaryMutation.isPending ? "💾 Saving..." : "💾 Save Summary"}
              </Button>
            )}
          </div>
        </div>
      )}

      {/* Footer */}
      <div
        style={{
          marginTop: "80px",
          padding: "40px 20px",
          textAlign: "center",
          borderTop: "2px solid #d4a574",
          color: "#8b7355",
        }}
      >
        <p style={{ margin: "0 0 12px", fontSize: "14px" }}>
          📧 Feedback: deepakg151089@gmail.com
        </p>
        <p style={{ margin: "0 0 20px", fontSize: "14px" }}>
          📞 Contact: Deepak Gupta - 8840778831
        </p>
        <Button
          onClick={() => setLocation("/contact")}
          style={{
            padding: "10px 20px",
            background: "transparent",
            color: "#d4a574",
            border: "2px solid #d4a574",
            borderRadius: "8px",
            fontWeight: "bold",
            cursor: "pointer",
          }}
        >
          💬 Feedback Form
        </Button>
      </div>
    </div>
  );
}
